CREATE OR ALTER TABLE SF_METRICS.DYNAMIC_TABLE_FACT (
  LOGDATE DATE
  , DATABASE_NAME VARCHAR
  , SCHEMA_NAME VARCHAR
  , TABLE_NAME VARCHAR
  , QUERY_ID VARCHAR
  , REFRESH_TRIGGER VARCHAR
  , REFRESH_ACTION VARCHAR
  , EVENTS_FULL INTEGER
  , EVENTS_INCREMENTAL INTEGER
  , EVENTS_NO_DATA INTEGER
  , TARGET_LAG_SEC INTEGER
  , STATE VARCHAR
  , STATE_CODE VARCHAR
  , STATE_MESSAGE VARCHAR
  , START_TIME TIMESTAMP_LTZ
  , END_TIME TIMESTAMP_LTZ
  , ROLE_NAME VARCHAR
  , WAREHOUSE_NAME VARCHAR
  , WAREHOUSE_SIZE VARCHAR
  , QUERY_CREDITS_USED FLOAT
  , CREDITS_ATTRIBUTED_COMPUTE FLOAT
  , CREDITS_USED_CLOUD_SERVICES FLOAT
  , TOTAL_ELAPSED_TIME INTEGER
  , QUEUED_OVERLOAD_TIME INTEGER
  , BYTES_SCANNED INTEGER
  , PARTITIONS_SCANNED INTEGER
  , PARTITIONS_TOTAL INTEGER
  , BYTES_SPILLED_TO_LOCAL_STORAGE VARCHAR
  , BYTES_SPILLED_TO_REMOTE_STORAGE INTEGER
  , ROWS_WRITTEN_TO_RESULT INTEGER
  , ROWS_INSERTED INTEGER
  , ROWS_UPDATED INTEGER
  , ROWS_DELETED INTEGER
)
COMMENT = 'Fact table for Dynamic Table Usage'
;
