CREATE OR ALTER TABLE SF_METRICS.QUERY_CREDITS (
LOGDATE DATE
, QUERY_ID VARCHAR
, QUERY_PARAMETERIZED_HASH VARCHAR
, SESSION_ID VARCHAR
, QUERY_TYPE VARCHAR
, USER_NAME VARCHAR
, ROLE_NAME VARCHAR
, WAREHOUSE_NAME VARCHAR
, QUERY_TAG VARCHAR
, QUERY_CREDITS_USED FLOAT
)
COMMENT = 'Credits proportioned out to queries'
;
