CREATE OR ALTER TRANSIENT TABLE SF_METRICS.TABLE_STORAGE_FACT (
  TABLE_CATALOG VARCHAR
  , TABLE_SCHEMA VARCHAR
  , TABLE_NAME VARCHAR
  , IS_TRANSIENT VARCHAR
  , COUNT_ACTIVE INTEGER
  , COUNT_DELETED INTEGER
  , ACTIVE_BYTES INTEGER
  , TIME_TRAVEL_BYTES INTEGER
  , FAILSAFE_BYTES INTEGER
  , RETAINED_FOR_CLONE_BYTES INTEGER
  , TOTAL_BYTES INTEGER
  , TIME_TRAVEL_X FLOAT
  , FAILSAFE_X FLOAT
  , TABLE_FIRST_CREATED TIMESTAMP_TZ
  , TABLE_LAST_DROPPED TIMESTAMP_TZ
)
COMMENT = 'Fact Table for storage of all tables'
;
