CREATE OR ALTER TABLE SF_METRICS.TASK_FACT (
LOGDATE DATE
, QUERY_ID VARCHAR
, SESSION_ID VARCHAR
, QUERY_PARAMETERIZED_HASH VARCHAR
, TASK_DATABASE VARCHAR
, TASK_SCHEMA VARCHAR
, TASK_NAME VARCHAR
, IS_ROOT BOOLEAN
, SCHEDULED_FROM VARCHAR
, ROLE_NAME VARCHAR
, WAREHOUSE_NAME VARCHAR
, WAREHOUSE_SIZE VARCHAR
, QUERY_CREDITS_USED FLOAT
, CREDITS_ATTRIBUTED_COMPUTE FLOAT
, CREDITS_SERVERLESS FLOAT
, CREDITS_USED_QUERY_ACCELERATION FLOAT
, EXECUTION_STATUS VARCHAR
, ERROR_CODE VARCHAR
, ERROR_MESSAGE VARCHAR
, START_TIME TIMESTAMP_LTZ
, END_TIME TIMESTAMP_LTZ
, TOTAL_ELAPSED_TIME INTEGER
, QUEUED_OVERLOAD_TIME INTEGER
, BYTES_SCANNED INTEGER
, PARTITIONS_SCANNED INTEGER
, PARTITIONS_TOTAL INTEGER
, BYTES_SPILLED_TO_LOCAL_STORAGE VARCHAR
, BYTES_SPILLED_TO_REMOTE_STORAGE INTEGER
, ROWS_WRITTEN_TO_RESULT INTEGER
, ROWS_INSERTED INTEGER
, ROWS_UPDATED INTEGER
, ROWS_DELETED INTEGER
, CREDITS_USED_CLOUD_SERVICES FLOAT
, COUNT_QUERIES INTEGER
)
COMMENT = 'Fact Table for Tasks'
;
