CREATE OR ALTER TABLE SF_METRICS.USER_QUERY_FACT (
LOGDATE DATE
, QUERY_ID VARCHAR
, SESSION_ID VARCHAR
, CONNECTOR_TYPE VARCHAR
, APPLICATION VARCHAR
, QUERY_PARAMETERIZED_HASH VARCHAR
, QUERY_TYPE VARCHAR
, USER_NAME VARCHAR
, ROLE_NAME VARCHAR
, WAREHOUSE_NAME VARCHAR
, WAREHOUSE_SIZE VARCHAR
, QUERY_TAG VARCHAR
, QUERY_TEXT VARCHAR
, QUERY_CREDITS_USED FLOAT
, CREDITS_ATTRIBUTED_COMPUTE FLOAT
, CREDITS_USED_QUERY_ACCELERATION FLOAT
, DATABASE_NAME VARCHAR
, SCHEMA_NAME VARCHAR
, EXECUTION_STATUS VARCHAR
, ERROR_CODE VARCHAR
, ERROR_MESSAGE VARCHAR
, START_TIME TIMESTAMP_LTZ
, END_TIME TIMESTAMP_LTZ
, TOTAL_ELAPSED_TIME INTEGER
, BYTES_SCANNED INTEGER
, PARTITIONS_SCANNED INTEGER
, PARTITIONS_TOTAL INTEGER
, QUERY_ACCELERATION_BYTES_SCANNED INTEGER
, BYTES_SPILLED_TO_LOCAL_STORAGE VARCHAR
, BYTES_SPILLED_TO_REMOTE_STORAGE INTEGER
, ROWS_WRITTEN_TO_RESULT INTEGER
, ROWS_INSERTED INTEGER
, ROWS_UPDATED INTEGER
, ROWS_DELETED INTEGER
, COMPILATION_TIME INTEGER
, EXECUTION_TIME INTEGER
, CREDITS_USED_CLOUD_SERVICES FLOAT
, QUERY_LOAD_PERCENT INTEGER
)
COMMENT = 'Fact Table for User (non System) queries'
;
