CREATE OR REPLACE VIEW SF_METRICS.V_DYNAMIC_TABLE_FACT (
  LOGDATE
  , DATABASE_NAME
  , SCHEMA_NAME
  , TABLE_NAME
  , QUERY_ID
  , REFRESH_TRIGGER
  , REFRESH_ACTION
  , EVENTS_FULL
  , EVENTS_INCREMENTAL
  , EVENTS_NO_DATA
  , TARGET_LAG_SEC
  , STATE
  , STATE_CODE
  , STATE_MESSAGE
  , START_TIME
  , END_TIME
  , ROLE_NAME
  , WAREHOUSE_NAME
  , WAREHOUSE_SIZE
  , QUERY_CREDITS_USED
  , CREDITS_ATTRIBUTED_COMPUTE
  , CREDITS_USED_CLOUD_SERVICES
  , TOTAL_ELAPSED_TIME
  , QUEUED_OVERLOAD_TIME
  , BYTES_SCANNED
  , PARTITIONS_SCANNED
  , PARTITIONS_TOTAL
  , BYTES_SPILLED_TO_LOCAL_STORAGE
  , BYTES_SPILLED_TO_REMOTE_STORAGE
  , ROWS_WRITTEN_TO_RESULT
  , ROWS_INSERTED
  , ROWS_UPDATED
  , ROWS_DELETED
)
COMMENT = 'Fact table for Dynamic Table Usage'
AS
SELECT
  LOGDATE
  , DATABASE_NAME
  , SCHEMA_NAME
  , TABLE_NAME
  , QUERY_ID
  , REFRESH_TRIGGER
  , REFRESH_ACTION
  , EVENTS_FULL
  , EVENTS_INCREMENTAL
  , EVENTS_NO_DATA
  , TARGET_LAG_SEC
  , STATE
  , STATE_CODE
  , STATE_MESSAGE
  , START_TIME
  , END_TIME
  , ROLE_NAME
  , WAREHOUSE_NAME
  , WAREHOUSE_SIZE
  , QUERY_CREDITS_USED
  , CREDITS_ATTRIBUTED_COMPUTE
  , CREDITS_USED_CLOUD_SERVICES
  , TOTAL_ELAPSED_TIME
  , QUEUED_OVERLOAD_TIME
  , BYTES_SCANNED
  , PARTITIONS_SCANNED
  , PARTITIONS_TOTAL
  , BYTES_SPILLED_TO_LOCAL_STORAGE
  , BYTES_SPILLED_TO_REMOTE_STORAGE
  , ROWS_WRITTEN_TO_RESULT
  , ROWS_INSERTED
  , ROWS_UPDATED
  , ROWS_DELETED
FROM SF_METRICS.DYNAMIC_TABLE_FACT
;
