CREATE OR REPLACE VIEW SF_METRICS.V_QUERY_CREDITS (
LOGDATE
, QUERY_ID
, QUERY_PARAMETERIZED_HASH
, SESSION_ID
, QUERY_TYPE
, USER_NAME
, ROLE_NAME
, WAREHOUSE_NAME
, QUERY_TAG
, QUERY_CREDITS_USED
)
COMMENT = 'Credits proportioned out to queries'
AS
SELECT
  LOGDATE
  , QUERY_ID
  , QUERY_PARAMETERIZED_HASH
  , SESSION_ID
  , QUERY_TYPE
  , USER_NAME
  , ROLE_NAME
  , WAREHOUSE_NAME
  , QUERY_TAG
  , QUERY_CREDITS_USED
FROM SF_METRICS.QUERY_CREDITS
;
