CREATE OR REPLACE VIEW SF_METRICS.V_TABLE_STORAGE_FACT (
  TABLE_CATALOG
  , TABLE_SCHEMA
  , TABLE_NAME
  , IS_TRANSIENT
  , COUNT_ACTIVE
  , COUNT_DELETED
  , ACTIVE_BYTES
  , TIME_TRAVEL_BYTES
  , FAILSAFE_BYTES
  , RETAINED_FOR_CLONE_BYTES
  , TOTAL_BYTES
  , TIME_TRAVEL_X
  , FAILSAFE_X
  , TABLE_FIRST_CREATED
  , TABLE_LAST_DROPPED
)
COMMENT = 'Fact Table for storage of all tables'
AS
SELECT
  TABLE_CATALOG
  , TABLE_SCHEMA
  , TABLE_NAME
  , IS_TRANSIENT
  , COUNT_ACTIVE
  , COUNT_DELETED
  , ACTIVE_BYTES
  , TIME_TRAVEL_BYTES
  , FAILSAFE_BYTES
  , RETAINED_FOR_CLONE_BYTES
  , TOTAL_BYTES
  , TIME_TRAVEL_X
  , FAILSAFE_X
  , TABLE_FIRST_CREATED
  , TABLE_LAST_DROPPED
FROM SF_METRICS.TABLE_STORAGE_FACT
;
