CREATE OR REPLACE VIEW SF_METRICS.V_TASK_FACT (
LOGDATE
, QUERY_ID
, SESSION_ID
, QUERY_PARAMETERIZED_HASH
, TASK_DATABASE
, TASK_SCHEMA
, TASK_NAME
, IS_ROOT
, SCHEDULED_FROM
, ROLE_NAME
, WAREHOUSE_NAME
, WAREHOUSE_SIZE
, QUERY_CREDITS_USED
, CREDITS_ATTRIBUTED_COMPUTE
, CREDITS_SERVERLESS
, CREDITS_USED_QUERY_ACCELERATION
, EXECUTION_STATUS
, ERROR_CODE
, ERROR_MESSAGE
, START_TIME
, END_TIME
, TOTAL_ELAPSED_TIME
, QUEUED_OVERLOAD_TIME
, BYTES_SCANNED
, PARTITIONS_SCANNED
, PARTITIONS_TOTAL
, BYTES_SPILLED_TO_LOCAL_STORAGE
, BYTES_SPILLED_TO_REMOTE_STORAGE
, ROWS_WRITTEN_TO_RESULT
, ROWS_INSERTED
, ROWS_UPDATED
, ROWS_DELETED
, CREDITS_USED_CLOUD_SERVICES
, COUNT_QUERIES
)
COMMENT = 'Fact Table for Tasks'
AS
SELECT
  LOGDATE
  , QUERY_ID
  , SESSION_ID
  , QUERY_PARAMETERIZED_HASH
  , TASK_DATABASE
  , TASK_SCHEMA
  , TASK_NAME
  , IS_ROOT
  , SCHEDULED_FROM
  , ROLE_NAME
  , WAREHOUSE_NAME
  , WAREHOUSE_SIZE
  , QUERY_CREDITS_USED
  , CREDITS_ATTRIBUTED_COMPUTE
  , CREDITS_SERVERLESS
  , CREDITS_USED_QUERY_ACCELERATION
  , EXECUTION_STATUS
  , ERROR_CODE
  , ERROR_MESSAGE
  , START_TIME
  , END_TIME
  , TOTAL_ELAPSED_TIME
  , QUEUED_OVERLOAD_TIME
  , BYTES_SCANNED
  , PARTITIONS_SCANNED
  , PARTITIONS_TOTAL
  , BYTES_SPILLED_TO_LOCAL_STORAGE
  , BYTES_SPILLED_TO_REMOTE_STORAGE
  , ROWS_WRITTEN_TO_RESULT
  , ROWS_INSERTED
  , ROWS_UPDATED
  , ROWS_DELETED
  , CREDITS_USED_CLOUD_SERVICES
  , COUNT_QUERIES
FROM SF_METRICS.TASK_FACT
;
