CREATE OR REPLACE VIEW SF_METRICS.V_USER_QUERY_FACT (
LOGDATE
, QUERY_ID
, SESSION_ID
, CONNECTOR_TYPE
, APPLICATION
, QUERY_PARAMETERIZED_HASH
, QUERY_TYPE
, USER_NAME
, ROLE_NAME
, WAREHOUSE_NAME
, WAREHOUSE_SIZE
, QUERY_TAG
, QUERY_TEXT
, QUERY_CREDITS_USED
, CREDITS_ATTRIBUTED_COMPUTE
, CREDITS_USED_QUERY_ACCELERATION
, DATABASE_NAME
, SCHEMA_NAME
, EXECUTION_STATUS
, ERROR_CODE
, ERROR_MESSAGE
, START_TIME
, END_TIME
, TOTAL_ELAPSED_TIME
, BYTES_SCANNED
, PARTITIONS_SCANNED
, PARTITIONS_TOTAL
, QUERY_ACCELERATION_BYTES_SCANNED
, BYTES_SPILLED_TO_LOCAL_STORAGE
, BYTES_SPILLED_TO_REMOTE_STORAGE
, ROWS_WRITTEN_TO_RESULT
, ROWS_INSERTED
, ROWS_UPDATED
, ROWS_DELETED
, COMPILATION_TIME
, EXECUTION_TIME
, CREDITS_USED_CLOUD_SERVICES
, QUERY_LOAD_PERCENT
)
COMMENT = 'Fact Table for User (non System) queries'
AS
SELECT
  LOGDATE
  , QUERY_ID
  , SESSION_ID
  , CONNECTOR_TYPE
  , APPLICATION
  , QUERY_PARAMETERIZED_HASH
  , QUERY_TYPE
  , USER_NAME
  , ROLE_NAME
  , WAREHOUSE_NAME
  , WAREHOUSE_SIZE
  , QUERY_TAG
  , QUERY_TEXT
  , QUERY_CREDITS_USED
  , CREDITS_ATTRIBUTED_COMPUTE
  , CREDITS_USED_QUERY_ACCELERATION
  , DATABASE_NAME
  , SCHEMA_NAME
  , EXECUTION_STATUS
  , ERROR_CODE
  , ERROR_MESSAGE
  , START_TIME
  , END_TIME
  , TOTAL_ELAPSED_TIME
  , BYTES_SCANNED
  , PARTITIONS_SCANNED
  , PARTITIONS_TOTAL
  , QUERY_ACCELERATION_BYTES_SCANNED
  , BYTES_SPILLED_TO_LOCAL_STORAGE
  , BYTES_SPILLED_TO_REMOTE_STORAGE
  , ROWS_WRITTEN_TO_RESULT
  , ROWS_INSERTED
  , ROWS_UPDATED
  , ROWS_DELETED
  , COMPILATION_TIME
  , EXECUTION_TIME
  , CREDITS_USED_CLOUD_SERVICES
  , QUERY_LOAD_PERCENT
FROM SF_METRICS.USER_QUERY_FACT
;
