CREATE OR REPLACE TASK SF_METRICS.T_ARCHIVE_TABLES
WAREHOUSE=XSMALL_WAREHOUSE_GOES_HERE
SCHEDULE='USING CRON 40 6,18 * * * America/Chicago'
COMMENT='Archive ACCOUNT_USAGE tables'
USER_TASK_TIMEOUT_MS=7200000
AS
BEGIN
  ASYNC (CALL SF_METRICS.P_DYNAMIC_TABLE_REFRESH_HISTORY());
  ASYNC (CALL SF_METRICS.P_QUERY_ATTRIBUTION_HISTORY());
  ASYNC (CALL SF_METRICS.P_QUERY_HISTORY());
  ASYNC (CALL SF_METRICS.P_SERVERLESS_TASK_HISTORY());
  ASYNC (CALL SF_METRICS.P_SESSIONS());
  ASYNC (CALL SF_METRICS.P_TASK_HISTORY());
  ASYNC (CALL SF_METRICS.P_USERS());
  ASYNC (CALL SF_METRICS.P_WAREHOUSE_METERING_HISTORY());

  AWAIT ALL;
END
;
