CREATE OR REPLACE TASK SF_METRICS.T_METRICS_TABLES
WAREHOUSE=XSMALL_WAREHOUSE_GOES_HERE
COMMENT='Populate SF_METRICS Data'
USER_TASK_TIMEOUT_MS=7200000
AFTER T_ARCHIVE_TABLES
AS
BEGIN
  CALL SF_METRICS.P_QUERY_CREDITS();

  ASYNC (CALL SF_METRICS.P_DYNAMIC_TABLE_FACT());
  ASYNC (CALL SF_METRICS.P_TABLE_STORAGE_FACT());
  ASYNC (CALL SF_METRICS.P_TASK_FACT());
  ASYNC (CALL SF_METRICS.P_USER_QUERY_FACT());

  AWAIT ALL;
END
;
