CREATE OR REPLACE PROCEDURE SF_METRICS.P_DYNAMIC_TABLE_FACT (DAYS_START INTEGER DEFAULT 2, DAYS_END INTEGER DEFAULT 0)
RETURNS VARIANT
LANGUAGE SQL
COMMENT = 'Update a Fact table for Dynamic Tables'
AS
$$
BEGIN
  INSERT INTO SF_METRICS.DYNAMIC_TABLE_FACT (
    LOGDATE
    , DATABASE_NAME
    , SCHEMA_NAME
    , TABLE_NAME
    , QUERY_ID
    , REFRESH_TRIGGER
    , REFRESH_ACTION
    , EVENTS_FULL
    , EVENTS_INCREMENTAL
    , EVENTS_NO_DATA
    , TARGET_LAG_SEC
    , STATE
    , STATE_CODE
    , STATE_MESSAGE
    , START_TIME
    , END_TIME
    , ROLE_NAME
    , WAREHOUSE_NAME
    , WAREHOUSE_SIZE
    , QUERY_CREDITS_USED
    , CREDITS_ATTRIBUTED_COMPUTE
    , CREDITS_USED_CLOUD_SERVICES
    , TOTAL_ELAPSED_TIME
    , QUEUED_OVERLOAD_TIME
    , BYTES_SCANNED
    , PARTITIONS_SCANNED
    , PARTITIONS_TOTAL
    , BYTES_SPILLED_TO_LOCAL_STORAGE
    , BYTES_SPILLED_TO_REMOTE_STORAGE
    , ROWS_WRITTEN_TO_RESULT
    , ROWS_INSERTED
    , ROWS_UPDATED
    , ROWS_DELETED
  )
  WITH
    dyn_tables as (
      SELECT
        LOGDATE
        , NAME as TABLE_NAME
        , SCHEMA_NAME
        , DATABASE_NAME
        , QUERY_ID
        , STATE
        , STATE_CODE
        , STATE_MESSAGE
        , REFRESH_ACTION
        , REFRESH_TRIGGER
        , TARGET_LAG_SEC
      FROM SF_METRICS.DYNAMIC_TABLE_REFRESH_HISTORY
      WHERE
        LOGDATE >= CURRENT_DATE() - :DAYS_START
        AND LOGDATE < CURRENT_DATE() - :DAYS_END
        AND QUERY_ID NOT IN (
          SELECT QUERY_ID
          FROM SF_METRICS.DYNAMIC_TABLE_FACT
          WHERE LOGDATE >= CURRENT_DATE() - :DAYS_START AND LOGDATE < CURRENT_DATE() - :DAYS_END
        )
    ),
    queries as (
      SELECT
        QUERY_ID
        , ROLE_NAME
        , WAREHOUSE_NAME
        , WAREHOUSE_SIZE
        , START_TIME
        , END_TIME
        , TOTAL_ELAPSED_TIME
        , QUEUED_OVERLOAD_TIME
        , BYTES_SCANNED
        , PARTITIONS_SCANNED
        , PARTITIONS_TOTAL
        , BYTES_SPILLED_TO_LOCAL_STORAGE
        , BYTES_SPILLED_TO_REMOTE_STORAGE
        , CREDITS_USED_CLOUD_SERVICES
        , ROWS_WRITTEN_TO_RESULT
        , ROWS_INSERTED
        , ROWS_UPDATED
        , ROWS_DELETED
      FROM SF_METRICS.QUERY_HISTORY
      WHERE QUERY_TYPE = 'REFRESH_DYNAMIC_TABLE_AT_REFRESH_VERSION'
        AND QUERY_ID IN (SELECT QUERY_ID FROM dyn_tables)
        AND LOGDATE >= CURRENT_DATE() - :DAYS_START
        AND LOGDATE < CURRENT_DATE() - :DAYS_END
    ),
    query_credits as (
      SELECT
        QUERY_ID
        , SUM(QUERY_CREDITS_USED) as QUERY_CREDITS_USED
      FROM SF_METRICS.QUERY_CREDITS
      WHERE QUERY_ID IN (SELECT QUERY_ID FROM dyn_tables)
        AND LOGDATE >= CURRENT_DATE() - :DAYS_START
        AND LOGDATE < CURRENT_DATE() - :DAYS_END
      GROUP BY QUERY_ID
    ),
    attributed as (
      SELECT
        QUERY_ID
        , SUM(CREDITS_ATTRIBUTED_COMPUTE) as CREDITS_ATTRIBUTED_COMPUTE
      FROM SF_METRICS.QUERY_ATTRIBUTION_HISTORY
      WHERE QUERY_ID IN (SELECT QUERY_ID from dyn_tables)
        AND LOGDATE >= CURRENT_DATE() - :DAYS_START
        AND LOGDATE < CURRENT_DATE() - :DAYS_END
      GROUP BY QUERY_ID
    )
  SELECT
    dyn_tables.LOGDATE
    , dyn_tables.DATABASE_NAME
    , dyn_tables.SCHEMA_NAME
    , dyn_tables.TABLE_NAME
    , dyn_tables.QUERY_ID
    , dyn_tables.REFRESH_TRIGGER
    , dyn_tables.REFRESH_ACTION
    , CASE WHEN REFRESH_ACTION = 'FULL' THEN 1 ELSE 0 END as EVENTS_FULL
    , CASE WHEN REFRESH_ACTION = 'INCREMENTAL' THEN 1 ELSE 0 END as EVENTS_INCREMENTAL
    , CASE WHEN REFRESH_ACTION = 'NO_DATA' THEN 1 ELSE 0 END as EVENTS_NO_DATA
    , dyn_tables.TARGET_LAG_SEC
    , dyn_tables.STATE
    , dyn_tables.STATE_CODE
    , dyn_tables.STATE_MESSAGE
    , queries.START_TIME
    , queries.END_TIME
    , queries.ROLE_NAME
    , queries.WAREHOUSE_NAME
    , queries.WAREHOUSE_SIZE
    , query_credits.QUERY_CREDITS_USED
    , attributed.CREDITS_ATTRIBUTED_COMPUTE
    , queries.CREDITS_USED_CLOUD_SERVICES
    , queries.TOTAL_ELAPSED_TIME
    , queries.QUEUED_OVERLOAD_TIME
    , queries.BYTES_SCANNED
    , queries.PARTITIONS_SCANNED
    , queries.PARTITIONS_TOTAL
    , queries.BYTES_SPILLED_TO_LOCAL_STORAGE
    , queries.BYTES_SPILLED_TO_REMOTE_STORAGE
    , queries.ROWS_WRITTEN_TO_RESULT
    , queries.ROWS_INSERTED
    , queries.ROWS_UPDATED
    , queries.ROWS_DELETED
  FROM dyn_tables
  INNER JOIN queries
    ON (dyn_tables.QUERY_ID = queries.QUERY_ID)
  LEFT JOIN query_credits
    ON(dyn_tables.QUERY_ID = query_credits.QUERY_ID)
  LEFT JOIN attributed
    ON (dyn_tables.QUERY_ID = attributed.QUERY_ID)
  ;

  RETURN TRUE;
EXCEPTION
  WHEN OTHER THEN
    RAISE;
END;
$$
;
