CREATE OR REPLACE PROCEDURE SF_METRICS.P_TABLE_STORAGE_FACT()
RETURNS VARIANT
LANGUAGE SQL
COMMENT = 'Populates TABLE_STORAGE_FACT with updated data'
AS
$$
BEGIN
  INSERT OVERWRITE INTO SF_METRICS.TABLE_STORAGE_FACT (
    TABLE_CATALOG
    , TABLE_SCHEMA
    , TABLE_NAME
    , IS_TRANSIENT
    , COUNT_ACTIVE
    , COUNT_DELETED
    , ACTIVE_BYTES
    , TIME_TRAVEL_BYTES
    , FAILSAFE_BYTES
    , RETAINED_FOR_CLONE_BYTES
    , TOTAL_BYTES
    , TIME_TRAVEL_X
    , FAILSAFE_X
    , TABLE_FIRST_CREATED
    , TABLE_LAST_DROPPED
  )
  SELECT
    TABLE_CATALOG
    , TABLE_SCHEMA
    , TABLE_NAME
    , IS_TRANSIENT
    , SUM(CASE WHEN deleted = true THEN 0 ELSE 1 END) as COUNT_ACTIVE
    , SUM(CASE WHEN deleted = true THEN 1 ELSE 0 END) as COUNT_DELETED
    , SUM(ACTIVE_BYTES) as ACTIVE_BYTES
    , SUM(TIME_TRAVEL_BYTES) as TIME_TRAVEL_BYTES
    , SUM(FAILSAFE_BYTES) as FAILSAFE_BYTES
    , SUM(RETAINED_FOR_CLONE_BYTES) as RETAINED_FOR_CLONE_BYTES
    , SUM(ACTIVE_BYTES + TIME_TRAVEL_BYTES + FAILSAFE_BYTES + RETAINED_FOR_CLONE_BYTES) as TOTAL_BYTES
    , ROUND(DIV0(SUM(TIME_TRAVEL_BYTES), SUM(ACTIVE_BYTES)), 2) as TIME_TRAVEL_X
    , ROUND(DIV0(SUM(FAILSAFE_BYTES), SUM(ACTIVE_BYTES)), 2) as FAILSAFE_X
    , MIN(TABLE_CREATED) as TABLE_FIRST_CREATED
    , MAX(TABLE_DROPPED) as TABLE_LAST_DROPPED
  FROM SNOWFLAKE.ACCOUNT_USAGE.TABLE_STORAGE_METRICS
  WHERE
    -- always include non active bytes
    (TIME_TRAVEL_BYTES + FAILSAFE_BYTES + RETAINED_FOR_CLONE_BYTES) > 0
    OR (
      -- conditionally include active bytes to filter out some noise
      ACTIVE_BYTES > 0
        AND (
          -- table still active
          TABLE_DROPPED IS NULL
          -- remove short lived temporary tables where active bytes not yet rolled off
          -- introduces data latency but cleans up meaningless records
          OR TABLE_CREATED < DATEADD('hours', -6, CURRENT_TIMESTAMP())
      )
    )
  GROUP BY
    TABLE_CATALOG
    , TABLE_SCHEMA
    , TABLE_NAME
    , IS_TRANSIENT
  ;

  RETURN TRUE;
EXCEPTION
  WHEN OTHER THEN
    RAISE;
END;
$$
;
