CREATE OR REPLACE PROCEDURE SF_METRICS.P_USER_QUERY_FACT (DAYS_START INTEGER DEFAULT 2, DAYS_END INTEGER DEFAULT 0)
RETURNS VARIANT
LANGUAGE SQL
COMMENT = 'Update a Fact table for User Queries'
AS
$$
BEGIN
  INSERT INTO SF_METRICS.USER_QUERY_FACT (
    LOGDATE
    , QUERY_ID
    , SESSION_ID
    , CONNECTOR_TYPE
    , APPLICATION
    , QUERY_PARAMETERIZED_HASH
    , QUERY_TYPE
    , USER_NAME
    , ROLE_NAME
    , WAREHOUSE_NAME
    , WAREHOUSE_SIZE
    , QUERY_TAG
    , QUERY_TEXT
    , QUERY_CREDITS_USED
    , CREDITS_ATTRIBUTED_COMPUTE
    , CREDITS_USED_QUERY_ACCELERATION
    , DATABASE_NAME
    , SCHEMA_NAME
    , EXECUTION_STATUS
    , ERROR_CODE
    , ERROR_MESSAGE
    , START_TIME
    , END_TIME
    , TOTAL_ELAPSED_TIME
    , BYTES_SCANNED
    , PARTITIONS_SCANNED
    , PARTITIONS_TOTAL
    , QUERY_ACCELERATION_BYTES_SCANNED
    , BYTES_SPILLED_TO_LOCAL_STORAGE
    , BYTES_SPILLED_TO_REMOTE_STORAGE
    , ROWS_WRITTEN_TO_RESULT
    , ROWS_INSERTED
    , ROWS_UPDATED
    , ROWS_DELETED
    , COMPILATION_TIME
    , EXECUTION_TIME
    , CREDITS_USED_CLOUD_SERVICES
    , QUERY_LOAD_PERCENT
  )
  WITH
    qc as (
      SELECT
        QUERY_ID
        , SUM(QUERY_CREDITS_USED) as QUERY_CREDITS_USED
      FROM SF_METRICS.QUERY_CREDITS
      WHERE
        LOGDATE >= CURRENT_DATE() - :DAYS_START
        AND LOGDATE < CURRENT_DATE() - :DAYS_END
        AND USER_NAME <> 'SYSTEM'
      GROUP BY QUERY_ID
    ),
    sess as (
      SELECT
        SESSION_ID
        , SPLIT_PART(CLIENT_APPLICATION_ID, ' ', 1) as CONNECTOR_TYPE
        , PARSE_JSON(CLIENT_ENVIRONMENT):APPLICATION::varchar as APPLICATION
      FROM SF_METRICS.SESSIONS
      WHERE
        LOGDATE >= CURRENT_DATE() - :DAYS_START
        AND LOGDATE < CURRENT_DATE() - :DAYS_END
        AND USER_NAME <> 'SYSTEM'
    ),
    attr as (
      SELECT
        QUERY_ID
        , CREDITS_ATTRIBUTED_COMPUTE
        , CREDITS_USED_QUERY_ACCELERATION
      FROM SF_METRICS.QUERY_ATTRIBUTION_HISTORY
      WHERE
        LOGDATE >= CURRENT_DATE() - :DAYS_START
        AND LOGDATE < CURRENT_DATE() - :DAYS_END
        AND USER_NAME <> 'SYSTEM'
    )
  SELECT
    qh.LOGDATE
    , qh.QUERY_ID
    , qh.SESSION_ID
    , sess.CONNECTOR_TYPE
    , sess.APPLICATION
    , qh.QUERY_PARAMETERIZED_HASH
    , qh.QUERY_TYPE
    , qh.USER_NAME
    , qh.ROLE_NAME
    , qh.WAREHOUSE_NAME
    , qh.WAREHOUSE_SIZE
    , qh.QUERY_TAG
    , qh.QUERY_TEXT
    , qc.QUERY_CREDITS_USED
    , attr.CREDITS_ATTRIBUTED_COMPUTE
    , attr.CREDITS_USED_QUERY_ACCELERATION
    , qh.DATABASE_NAME
    , qh.SCHEMA_NAME
    , qh.EXECUTION_STATUS
    , qh.ERROR_CODE
    , qh.ERROR_MESSAGE
    , qh.START_TIME
    , qh.END_TIME
    , qh.TOTAL_ELAPSED_TIME
    , qh.BYTES_SCANNED
    , qh.PARTITIONS_SCANNED
    , qh.PARTITIONS_TOTAL
    , qh.QUERY_ACCELERATION_BYTES_SCANNED
    , qh.BYTES_SPILLED_TO_LOCAL_STORAGE
    , qh.BYTES_SPILLED_TO_REMOTE_STORAGE
    , qh.ROWS_WRITTEN_TO_RESULT
    , qh.ROWS_INSERTED
    , qh.ROWS_UPDATED
    , qh.ROWS_DELETED
    , qh.COMPILATION_TIME
    , qh.EXECUTION_TIME
    , qh.CREDITS_USED_CLOUD_SERVICES
    , qh.QUERY_LOAD_PERCENT
  FROM
    SF_METRICS.QUERY_HISTORY qh
    LEFT JOIN qc
      ON (qh.QUERY_ID = qc.QUERY_ID)
    LEFT JOIN sess
      ON (qh.SESSION_ID = sess.SESSION_ID)
    LEFT JOIN attr
      ON (qh.QUERY_ID = attr.QUERY_ID)
  WHERE
    qh.LOGDATE >= CURRENT_DATE() - :DAYS_START
    AND qh.LOGDATE < CURRENT_DATE() - :DAYS_END
    AND qh.USER_NAME NOT IN ('SYSTEM', 'WORKSHEETS_APP_USER')
    AND qh.QUERY_ID NOT IN (
      SELECT QUERY_ID
      FROM SF_METRICS.USER_QUERY_FACT
      WHERE LOGDATE >= CURRENT_DATE() - :DAYS_START AND LOGDATE < CURRENT_DATE() - :DAYS_END
    )
  ;

  RETURN TRUE;
EXCEPTION
  WHEN OTHER THEN
    RAISE;
END;
$$
;
