CREATE OR REPLACE VIEW SF_METRICS.V_AUTOMATIC_CLUSTERING_HISTORY (
  START_TIME
  , END_TIME
  , CREDITS_USED
  , NUM_BYTES_RECLUSTERED
  , NUM_ROWS_RECLUSTERED
  , TABLE_ID
  , TABLE_NAME
  , SCHEMA_ID
  , SCHEMA_NAME
  , DATABASE_ID
  , DATABASE_NAME
  , INSTANCE_ID
)
AS
SELECT
  START_TIME
  , END_TIME
  , CREDITS_USED
  , NUM_BYTES_RECLUSTERED
  , NUM_ROWS_RECLUSTERED
  , TABLE_ID
  , TABLE_NAME
  , SCHEMA_ID
  , SCHEMA_NAME
  , DATABASE_ID
  , DATABASE_NAME
  , INSTANCE_ID
FROM SNOWFLAKE.ACCOUNT_USAGE.AUTOMATIC_CLUSTERING_HISTORY
;
