CREATE OR REPLACE VIEW SF_METRICS.V_CORTEX_SEARCH_DAILY_USAGE_HISTORY (
  USAGE_DATE
  , DATABASE_NAME
  , SCHEMA_NAME
  , SERVICE_NAME
  , SERVICE_ID
  , CONSUMPTION_TYPE
  , CREDITS
  , MODEL_NAME
  , TOKENS
)
AS
SELECT
  USAGE_DATE
  , DATABASE_NAME
  , SCHEMA_NAME
  , SERVICE_NAME
  , SERVICE_ID
  , CONSUMPTION_TYPE
  , CREDITS
  , MODEL_NAME
  , TOKENS
FROM SNOWFLAKE.ACCOUNT_USAGE.CORTEX_SEARCH_DAILY_USAGE_HISTORY
;
