CREATE OR REPLACE VIEW SF_METRICS.V_CORTEX_AISQL_USAGE_HISTORY (
  LOGDATE
  , USAGE_TIME
  , MODEL_NAME
  , FUNCTION_NAME
  , TOKEN_CREDITS
  , TOKENS
  , TOKEN_CREDITS_GRANULAR
  , TOKENS_GRANULAR
  , QUERY_ID
  , QUERY_TAG
  , USER_ID
  , WAREHOUSE_ID
  , INPUT_TOKENS
  , OUTPUT_TOKENS
)
AS
SELECT
  DATE_TRUNC('day', USAGE_TIME) as LOGDATE
  , USAGE_TIME
  , MODEL_NAME
  , FUNCTION_NAME
  , TOKEN_CREDITS
  , TOKENS
  , TOKEN_CREDITS_GRANULAR
  , TOKENS_GRANULAR
  , QUERY_ID
  , QUERY_TAG
  , USER_ID
  , WAREHOUSE_ID
  , TOKENS_GRANULAR:input as INPUT_TOKENS
  , TOKENS_GRANULAR:output as OUTPUT_TOKENS
FROM SNOWFLAKE.ACCOUNT_USAGE.CORTEX_AISQL_USAGE_HISTORY
;
