CREATE OR REPLACE VIEW SF_METRICS.V_CORTEX_REST_API_USAGE_HISTORY (
  LOGDATE
  , START_TIME
  , END_TIME
  , REQUEST_ID
  , MODEL_NAME
  , TOKENS
  , TOKENS_GRANULAR
  , USER_ID
  , INFERENCE_REGION
  , INPUT_TOKENS
  , OUTPUT_TOKENS
  , CACHED_INPUT_TOKENS
)
AS
SELECT
  DATE_TRUNC('day', START_TIME) as LOGDATE
  , START_TIME
  , END_TIME
  , REQUEST_ID
  , MODEL_NAME
  , TOKENS
  , TOKENS_GRANULAR
  , USER_ID
  , INFERENCE_REGION
  , TOKENS_GRANULAR:input as INPUT_TOKENS
  , TOKENS_GRANULAR:output as OUTPUT_TOKENS
  , TOKENS_GRANULAR:cache_read_input as CACHED_INPUT_TOKENS
FROM SNOWFLAKE.ACCOUNT_USAGE.CORTEX_REST_API_USAGE_HISTORY
;
