CREATE OR REPLACE VIEW SF_METRICS.V_CORTEX_AGENT_USAGE_HISTORY (
  LOGDATE
  , START_TIME
  , END_TIME
  , USER_ID
  , USER_NAME
  , USER_TAGS
  , REQUEST_ID
  , PARENT_REQUEST_ID
  , AGENT_DATABASE_ID
  , AGENT_DATABASE_NAME
  , AGENT_SCHEMA_ID
  , AGENT_SCHEMA_NAME
  , AGENT_ID
  , AGENT_NAME
  , AGENT_TAGS
  , TOKEN_CREDITS
  , TOKENS
  , TOKENS_GRANULAR
  , CREDITS_GRANULAR
  , METADATA
)
AS
SELECT
  DATE_TRUNC('day', START_TIME) as LOGDATE
  , START_TIME
  , END_TIME
  , USER_ID
  , USER_NAME
  , USER_TAGS
  , REQUEST_ID
  , PARENT_REQUEST_ID
  , AGENT_DATABASE_ID
  , AGENT_DATABASE_NAME
  , AGENT_SCHEMA_ID
  , AGENT_SCHEMA_NAME
  , AGENT_ID
  , AGENT_NAME
  , AGENT_TAGS
  , TOKEN_CREDITS
  , TOKENS
  , TOKENS_GRANULAR
  , CREDITS_GRANULAR
  , METADATA
FROM SNOWFLAKE.ACCOUNT_USAGE.CORTEX_AGENT_USAGE_HISTORY
;
