CREATE OR REPLACE VIEW SF_METRICS.V_CORTEX_FUNCTIONS_USAGE_HISTORY (
  START_TIME
  , END_TIME
  , FUNCTION_NAME
  , MODEL_NAME
  , WAREHOUSE_ID
  , TOKENS
  , TOKEN_CREDITS
)
AS
SELECT
  START_TIME
  , END_TIME
  , FUNCTION_NAME
  , MODEL_NAME
  , WAREHOUSE_ID
  , TOKENS
  , TOKEN_CREDITS
FROM SNOWFLAKE.ACCOUNT_USAGE.CORTEX_FUNCTIONS_USAGE_HISTORY
;
