CREATE OR REPLACE VIEW SF_METRICS.V_CORTEX_CODE_CLI_USAGE_HISTORY (
  LOGDATE
  , USER_ID
  , USER_TAGS
  , REQUEST_ID
  , PARENT_REQUEST_ID
  , USAGE_TIME
  , TOKEN_CREDITS
  , TOKENS
  , TOKENS_GRANULAR
  , CREDITS_GRANULAR
)
AS
SELECT
  DATE_TRUNC('day', USAGE_TIME)::DATE as LOGDATE
  , USER_ID
  , USER_TAGS
  , REQUEST_ID
  , PARENT_REQUEST_ID
  , USAGE_TIME
  , TOKEN_CREDITS
  , TOKENS
  , TOKENS_GRANULAR
  , CREDITS_GRANULAR
FROM SNOWFLAKE.ACCOUNT_USAGE.CORTEX_CODE_CLI_USAGE_HISTORY
;
