CREATE OR REPLACE VIEW SF_METRICS.V_HYBRID_TABLE_USAGE_HISTORY (
  OBJECT_TYPE
  , OBJECT_ID
  , OBJECT_NAME
  , START_TIME
  , END_TIME
  , CREDITS_USED
)
AS
SELECT
  OBJECT_TYPE
  , OBJECT_ID
  , OBJECT_NAME
  , START_TIME
  , END_TIME
  , CREDITS_USED
FROM SNOWFLAKE.ACCOUNT_USAGE.HYBRID_TABLE_USAGE_HISTORY
;
