CREATE OR REPLACE VIEW SF_METRICS.V_MATERIALIZED_VIEW_REFRESH_HISTORY (
  START_TIME
  , END_TIME
  , CREDITS_USED
  , TABLE_ID
  , TABLE_NAME
  , SCHEMA_ID
  , SCHEMA_NAME
  , DATABASE_ID
  , DATABASE_NAME
)
AS
SELECT
  START_TIME
  , END_TIME
  , CREDITS_USED
  , TABLE_ID
  , TABLE_NAME
  , SCHEMA_ID
  , SCHEMA_NAME
  , DATABASE_ID
  , DATABASE_NAME
FROM SNOWFLAKE.ACCOUNT_USAGE.MATERIALIZED_VIEW_REFRESH_HISTORY
;
