CREATE OR REPLACE VIEW SF_METRICS.V_METERING_DAILY_HISTORY (
  SERVICE_TYPE
  , USAGE_DATE
  , CREDITS_USED_COMPUTE
  , CREDITS_USED_CLOUD_SERVICES
  , CREDITS_USED
  , CREDITS_ADJUSTMENT_CLOUD_SERVICES
  , CREDITS_BILLED
)
AS
SELECT
  SERVICE_TYPE
  , USAGE_DATE
  , CREDITS_USED_COMPUTE
  , CREDITS_USED_CLOUD_SERVICES
  , CREDITS_USED
  , CREDITS_ADJUSTMENT_CLOUD_SERVICES
  , CREDITS_BILLED
FROM SNOWFLAKE.ACCOUNT_USAGE.METERING_DAILY_HISTORY
;
