CREATE OR REPLACE VIEW SF_METRICS.V_SNOWPARK_CONTAINER_SERVICES_HISTORY (
  START_TIME
  , END_TIME
  , COMPUTE_POOL_NAME
  , IS_EXCLUSIVE
  , APPLICATION_NAME
  , APPLICATION_ID
  , CREDITS_USED
)
AS
SELECT
  START_TIME
  , END_TIME
  , COMPUTE_POOL_NAME
  , IS_EXCLUSIVE
  , APPLICATION_NAME
  , APPLICATION_ID
  , CREDITS_USED
FROM SNOWFLAKE.ACCOUNT_USAGE.SNOWPARK_CONTAINER_SERVICES_HISTORY
;
