CREATE OR REPLACE VIEW SF_METRICS.V_WAREHOUSE_EVENTS_HISTORY (
  TIMESTAMP
  , WAREHOUSE_ID
  , WAREHOUSE_NAME
  , CLUSTER_NUMBER
  , EVENT_NAME
  , EVENT_REASON
  , EVENT_STATE
  , USER_NAME
  , ROLE_NAME
  , QUERY_ID
  , SIZE
  , CLUSTER_COUNT
  , WAREHOUSE_TYPE
  , RESOURCE_CONSTRAINT
)
AS
SELECT
  TIMESTAMP
  , WAREHOUSE_ID
  , WAREHOUSE_NAME
  , CLUSTER_NUMBER
  , EVENT_NAME
  , EVENT_REASON
  , EVENT_STATE
  , USER_NAME
  , ROLE_NAME
  , QUERY_ID
  , SIZE
  , CLUSTER_COUNT
  , WAREHOUSE_TYPE
  , RESOURCE_CONSTRAINT
FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_EVENTS_HISTORY
;
